server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-ct22585umphs738sub00-a.oregon-postgres.render.com:5432/moodifydb_8xb3  # Use a URL externa
    username: moodifydb_8xb3_user  # Nome de usuário
    password: HFftUeitiA5DwtDpwUro6ZqyDQvCZ49F  # Senha do banco de dados
    driver-class-name: org.postgresql.Driver
    initialize: true

  jpa:
    hibernate:
      ddl-auto: create-drop  # Altere para 'update' se não quiser recriar o banco cada vez
      generate-ddl: true

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql  # Se você tiver um script de inicialização de schema
      mode: always
      platform: postgres