server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cperjq7sc6pc73a319ug-a:5432/fatecjava_3rbg // aqui ajusta para o link que está lá e o  nome do branco
        username: fatecjava // Coloca aqui o username do render
        password: rD7NIJNpRZhrqK0DkPpOTYTm6DT5wPbV // senha do render, user e senha são gerados lá 
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres

// Apagar o applicatino.properties e deixa só esse .yml e sobe lá